import { AttributeValueType } from '../components/commands/SetProjectAttributeValueCommand';
import { V3Axes } from './InterpretedLine';
import { IValue } from './IValue';
export declare const InterpretedLineConstantDefaultValue: readonly ["0"];
export declare const InterpretedLineOperatorDefaultValue: readonly ["0"];
export declare const INodePropertyNamesValues: readonly ["name", "MVName", "comment"];
export declare const IProductAttributeNamesValues: readonly ["ProductAttribute1", "ProductAttribute2", "ProductAttribute3", "FixedDepth", "FrontPosition", "InsetShelf", "FaceFrameWidth", "DoorOpenType", "DoorType", "DoorOpenDirection", "DoorOpenSide"];
export type IProductAttributeNames = (typeof IProductAttributeNamesValues)[number];
export declare const IProductPropertyNamesValues: readonly ["name", "MVName", "comment", "isFinishEnd", "catalogPath", "isFiller", "HideInCalculation", "isSingleCloset", "isMultiCloset", "isClosetShelf", "freePartsNonSelectable", "LeftMultiClosetNeighborId", "RightMultiClosetNeighborId", "LeftJointMultiClosetNeighborId", "RightJointMultiClosetNeighborId", "itemNumber"];
export declare const IPartPropertyNamesValues: readonly ["name", "MVName", "comment", "HideInCalculation", "catalogPath", "PanelPresent", "isLocked"];
export type IPartPropertyNames = (typeof IPartPropertyNamesValues)[number];
export declare const IPointPropertyNamesValues: readonly ["isLocked", "isAngleLocked"];
export type IPointPropertyNames = (typeof IPointPropertyNamesValues)[number];
export declare const IRoomSegmentPropertyNamesValues: readonly ["name", "MVName", "comment", "isLocked"];
export type IRoomSegmentPropertyNames = (typeof IRoomSegmentPropertyNamesValues)[number];
export type IProductPropertyNames = (typeof IProductPropertyNamesValues)[number];
export declare const IBoxContainerPropertyNamesValues: readonly ["name", "MVName", "comment", "shelfShape"];
export type IBoxContainerPropertyNames = (typeof IBoxContainerPropertyNamesValues)[number];
export declare const ICarcassAttributeNamesValues: readonly ["CarcassAttribute1", "CarcassAttribute2", "CarcassAttribute3"];
export type ICarcassAttributeNames = (typeof ICarcassAttributeNamesValues)[number];
export declare const IPartAttributeNamesValues: readonly ["PartAttribute1", "PartAttribute2", "PartAttribute3"];
export type IPartAttributeNames = (typeof IPartAttributeNamesValues)[number];
export declare const IPanelAttributeNamesValues: readonly ["PanelAttribute1", "PanelAttribute2", "PanelAttribute3"];
export type IPanelAttributeNames = (typeof IPanelAttributeNamesValues)[number];
export declare const IRoomAttributeNamesValues: readonly ["RoomAttribute1", "RoomAttribute2", "RoomAttribute3", "CeilingType", "DecoMoldingPresent", "DecoMoldingHeight", "BaseboardPresent", "BaseboardHeight", "BaseboardDepth", "BaseWallPoints", "CeilingWallPoints", "WallHeight", "returnWall"];
export type IRoomAttributeNames = (typeof IRoomAttributeNamesValues)[number];
export declare const IPanelProperyNamesValues: readonly ["name", "MVName", "comment", "PanelProperty1"];
export type IPanelPropertyNames = (typeof IPanelProperyNamesValues)[number];
export declare const IModelProperyNamesValues: readonly ["name", "MVName", "comment", "isScalable", "isPositioned", "isSizable"];
export type IModelPropertyNames = (typeof IModelProperyNamesValues)[number];
export type IPropertyNames = IProductPropertyNames | IBoxContainerPropertyNames | IPanelPropertyNames | IModelPropertyNames | IPointPropertyNames | IRoomSegmentPropertyNames;
export declare const ICountertopAttributeNamesValues: readonly ["CountertopAttribute1", "CountertopAttribute2", "CountertopAttribute3", "CountertopThickness"];
export type ICountertopAttributeNames = (typeof ICountertopAttributeNamesValues)[number];
export declare const IAttributeNamesValues: readonly ["ProductAttribute1", "ProductAttribute2", "ProductAttribute3", "FixedDepth", "FrontPosition", "InsetShelf", "FaceFrameWidth", "DoorOpenType", "DoorType", "DoorOpenDirection", "DoorOpenSide", "CarcassAttribute1", "CarcassAttribute2", "CarcassAttribute3", "PartAttribute1", "PartAttribute2", "PartAttribute3", "PanelAttribute1", "PanelAttribute2", "PanelAttribute3", "CountertopAttribute1", "CountertopAttribute2", "CountertopAttribute3", "CountertopThickness", "RoomAttribute1", "RoomAttribute2", "RoomAttribute3", "CeilingType", "DecoMoldingPresent", "DecoMoldingHeight", "BaseboardPresent", "BaseboardHeight", "BaseboardDepth", "BaseWallPoints", "CeilingWallPoints", "WallHeight", "returnWall"];
export type IAttributeNames = (typeof IAttributeNamesValues)[number];
export declare const IProjectAttributeNamesValues: readonly ["placeholder", "MultiClosetsJointType"];
export type IProjectAttributeNames = (typeof IProjectAttributeNamesValues)[number];
export declare const IMaterialsSetMaterialAttributeSValues: readonly ["placeholder"];
export type IMaterialsSetMaterialAttributeS = (typeof IMaterialsSetMaterialAttributeSValues)[number];
export declare const IMaterialsSetMaterialAttributeNValues: readonly ["placeholder"];
export type IMaterialsSetMaterialAttributeN = (typeof IMaterialsSetMaterialAttributeNValues)[number];
export declare const IMaterialsSetStyleAttributeSValues: readonly ["placeholder"];
export type IMaterialsSetStyleAttributeS = (typeof IMaterialsSetStyleAttributeSValues)[number];
export declare const IMaterialsSetStyleAttributeNValues: readonly ["placeholder"];
export type IMaterialsSetStyleAttributeN = (typeof IMaterialsSetStyleAttributeNValues)[number];
export declare const IMaterialsSetAttributeValueValues: readonly ["placeholder"];
export type IMaterialsSetAttributeValue = (typeof IMaterialsSetAttributeValueValues)[number];
export declare const IBoxContainerAttributeNamesValues: readonly [];
export type IBoxContainerAttributeNames = (typeof IBoxContainerAttributeNamesValues)[number];
export declare const ICrownMoldingAttributeNamesValues: readonly [];
export type ICrownMoldingAttributeNames = (typeof ICrownMoldingAttributeNamesValues)[number];
export declare const IEdgebandingAttributeNamesValues: readonly [];
export type IEdgebandingAttributeNames = (typeof IEdgebandingAttributeNamesValues)[number];
export declare const IFrameAttributeNamesValues: readonly [];
export type IFrameAttributeNames = (typeof IFrameAttributeNamesValues)[number];
export declare const IGateFrameAttributeNamesValues: readonly [];
export type IGateFrameAttributeNames = (typeof IGateFrameAttributeNamesValues)[number];
export declare const IGlassAttributeNamesValues: readonly [];
export type IGlassAttributeNames = (typeof IGlassAttributeNamesValues)[number];
export declare const IGroupContainerAttributeNamesValues: readonly [];
export type IGroupContainerAttributeNames = (typeof IGroupContainerAttributeNamesValues)[number];
export declare const IMiteredPanelAttributeNamesValues: readonly [];
export type IMiteredPanelAttributeNames = (typeof IMiteredPanelAttributeNamesValues)[number];
export declare const IModelAttributeNamesValues: readonly [];
export type IModelAttributeNames = (typeof IModelAttributeNamesValues)[number];
export declare const IMountPlaneAttributeNamesValues: readonly [];
export type IMountPlaneAttributeNames = (typeof IMountPlaneAttributeNamesValues)[number];
export declare const IMountPointAttributeNamesValues: readonly [];
export type IMountPointAttributeNames = (typeof IMountPointAttributeNamesValues)[number];
export declare const IPointLightAttributeNamesValues: readonly [];
export type IPointLightAttributeNames = (typeof IPointLightAttributeNamesValues)[number];
export declare const ISpotLightAttributeNamesValues: readonly [];
export type ISpotLightAttributeNames = (typeof ISpotLightAttributeNamesValues)[number];
export declare const IToeKickPanelAttributeNamesValues: readonly [];
export type IToeKickPanelAttributeNames = (typeof IToeKickPanelAttributeNamesValues)[number];
export declare const IValanceAttributeNamesValues: readonly [];
export type IValanceAttributeNames = (typeof IValanceAttributeNamesValues)[number];
export declare const IWindowFrameAttributeNamesValues: readonly [];
export type IWindowFrameAttributeNames = (typeof IWindowFrameAttributeNamesValues)[number];
export declare const InterpretedTypeValuesOptions: {
    readonly operator: readonly ["0"];
    readonly constant: readonly ["0"];
    readonly size: typeof V3Axes;
    readonly productSize: typeof V3Axes;
    readonly partSize: typeof V3Axes;
    readonly boxContainerSize: typeof V3Axes;
    readonly countertopSize: typeof V3Axes;
    readonly panelSize: typeof V3Axes;
    readonly carcassSize: typeof V3Axes;
    readonly partPosition: typeof V3Axes;
    readonly productAttribute: readonly ["ProductAttribute1", "ProductAttribute2", "ProductAttribute3", "FixedDepth", "FrontPosition", "InsetShelf", "FaceFrameWidth", "DoorOpenType", "DoorType", "DoorOpenDirection", "DoorOpenSide"];
    readonly boxContainerAttribute: readonly [];
    readonly carcassAttribute: readonly ["CarcassAttribute1", "CarcassAttribute2", "CarcassAttribute3"];
    readonly partAttribute: readonly ["PartAttribute1", "PartAttribute2", "PartAttribute3"];
    readonly panelAttribute: readonly ["PanelAttribute1", "PanelAttribute2", "PanelAttribute3"];
    readonly countertopAttribute: readonly ["CountertopAttribute1", "CountertopAttribute2", "CountertopAttribute3", "CountertopThickness"];
    readonly roomAttribute: readonly ["RoomAttribute1", "RoomAttribute2", "RoomAttribute3", "CeilingType", "DecoMoldingPresent", "DecoMoldingHeight", "BaseboardPresent", "BaseboardHeight", "BaseboardDepth", "BaseWallPoints", "CeilingWallPoints", "WallHeight", "returnWall"];
    readonly attribute: readonly ["ProductAttribute1", "ProductAttribute2", "ProductAttribute3", "FixedDepth", "FrontPosition", "InsetShelf", "FaceFrameWidth", "DoorOpenType", "DoorType", "DoorOpenDirection", "DoorOpenSide", "CarcassAttribute1", "CarcassAttribute2", "CarcassAttribute3", "PartAttribute1", "PartAttribute2", "PartAttribute3", "PanelAttribute1", "PanelAttribute2", "PanelAttribute3", "CountertopAttribute1", "CountertopAttribute2", "CountertopAttribute3", "CountertopThickness", "RoomAttribute1", "RoomAttribute2", "RoomAttribute3", "CeilingType", "DecoMoldingPresent", "DecoMoldingHeight", "BaseboardPresent", "BaseboardHeight", "BaseboardDepth", "BaseWallPoints", "CeilingWallPoints", "WallHeight", "returnWall"];
    readonly materialsSetAttribute: readonly string[];
    readonly projectAttribute: readonly ["placeholder", "MultiClosetsJointType"];
    readonly materialsSetMaterialAttributeS: readonly ["placeholder"];
    readonly materialsSetMaterialAttributeN: readonly ["placeholder"];
    readonly materialsSetStyleAttributeS: readonly ["placeholder"];
    readonly materialsSetStyleAttributeN: readonly ["placeholder"];
    readonly materialsSetAttributeValue: readonly ["placeholder"];
};
export type IAttributeValue = IValue<AttributeValueType>;
export type IAttributes = {
    [key: string]: IAttributeValue;
};
export type ICatalogAttributes = IAttributes | (string | IAttributes)[];
