var NodeType;
(function (NodeType) {
    NodeType["Floorplan"] = "Floorplan";
    NodeType["Item"] = "Item";
    NodeType["Panel"] = "Panel";
    NodeType["Part"] = "Part";
    NodeType["Edgebanding"] = "Edgebanding";
    NodeType["AdjustableBox"] = "AdjustableBox";
    NodeType["AdjustableExtrusion"] = "AdjustableExtrusion";
    NodeType["BoxContainer"] = "BoxContainer";
    NodeType["Carcass"] = "Carcass";
    NodeType["Countertop"] = "Countertop";
    NodeType["CrownMolding"] = "CrownMolding";
    NodeType["Frame"] = "Frame";
    NodeType["FreeBoxContainer"] = "FreeBoxContainer";
    NodeType["GateFrame"] = "GateFrame";
    NodeType["Glass"] = "Glass";
    NodeType["Image"] = "Image";
    NodeType["LaminateBox"] = "LaminateBox";
    NodeType["MiteredPanel"] = "MiteredPanel";
    NodeType["Model"] = "Model";
    NodeType["Molding"] = "Molding";
    NodeType["PointLight"] = "PointLight";
    NodeType["RawPanel"] = "RawPanel";
    NodeType["ShapedBoxContainer"] = "ShapedBoxContainer";
    NodeType["SpotLight"] = "SpotLight";
    NodeType["Tiles"] = "Tiles";
    NodeType["ToeKickPanel"] = "ToeKickPanel";
    NodeType["Valance"] = "Valance";
    NodeType["WindowFrame"] = "WindowFrame";
    NodeType["MountPoint"] = "MountPoint";
    NodeType["MountPlane"] = "MountPlane";
    NodeType["MountLine"] = "MountLine";
    NodeType["Room"] = "Room";
    NodeType["Stage"] = "Stage";
    NodeType["Point"] = "Point";
    NodeType["RoomSegment"] = "RoomSegment";
    NodeType["Wall2D"] = "Wall2D";
    NodeType["Floor2D"] = "Floor2D";
    NodeType["Ceiling2D"] = "Ceiling2D";
})(NodeType || (NodeType = {}));

export { NodeType };
