import { Vec2 } from '../helpers';
import { UUID } from './core';
import { inches } from './units';
export interface IElementVisibility {
    view: boolean;
    dimensions: boolean;
    blocks: boolean;
    traces: boolean;
    labels: boolean;
    lines: boolean;
    leaders: boolean;
    numbers: boolean;
    texts: boolean;
}
export type IPoint2d = {
    x: number;
    y: number;
};
export type sideType = 'top' | 'bottom' | 'left' | 'right';
export type viewType = 'floor' | 'wall' | 'multiClosetItem' | 'multiClosetFloor';
export type wallViewType = 'wallProductsOnly' | 'allVisibleProducts';
export type sizes = {
    width: number;
    height: number;
};
export type pointView = {
    u: number;
    v: number;
    x: number;
    y: number;
    wallId?: string;
};
export type pointViewExtended = pointView & {
    uuid: UUID;
    isLeftBottom?: boolean;
    isRightTop?: boolean;
};
export type itemView = {
    uuid: string;
    leftBottom: pointView;
    rightTop: pointView;
    labelPos?: pointView;
    MVName: string;
    name: string;
    itemNumber?: number | string;
    wallId?: string;
    sinkMount?: boolean;
};
export type wallView = {
    leftBottom: pointView;
    rightTop: pointView;
    normal: Vec2;
    thickness: number;
};
export type dimensions = {
    dpi: number;
    root: {
        uuid: string;
        type: viewType;
        vertices: pointView[];
        walls?: {
            [key: string]: wallView;
        };
    };
    cabinets: {
        upper: itemView[];
        tall: itemView[];
        base: itemView[];
    };
    appliances: {
        upper: itemView[];
        tall: itemView[];
        base: itemView[];
    };
    windows: itemView[];
    doors: itemView[];
};
export declare enum FloorCountertops {
    present = 1,
    hided = 2,
    only = 3
}
export type I2DViewSettings = {
    countertop?: {
        top: boolean;
    };
    floor?: {
        countertops: FloorCountertops;
        mergeItems?: boolean;
    };
    wallDistance?: number;
    wallViewType?: wallViewType;
    content: {
        offsetLeft: number;
        offsetRight: number;
        width: number;
        height: number;
    };
    camera: number[];
};
export type snapping = {
    [key: string]: any;
};
export declare enum EShapeType {
    Trace = "Trace",
    Text = "Text",
    Label = "Label",
    Leader = "Leader",
    Block = "Block",
    Line = "Line",
    Dimension = "Dimension",
    Number = "Number"
}
export type selectedShapeType = EShapeType | 'View';
export type IShape = {
    uuid: UUID;
    type: EShapeType;
    viewID: UUID;
    draggable?: boolean;
    fontSize?: number;
    textColor?: string;
    bgColor?: string;
    lineWidth?: number;
    lineColor?: string;
};
export type ILine = IShape & {
    from: IPoint2d;
    to: IPoint2d;
};
export type IDimension = ILine & {
    text?: string;
    padding?: number;
    isDragged: boolean;
    startPosition?: {
        from: IPoint2d;
        to: IPoint2d;
    };
    isAuto?: boolean;
    points?: IPoint2d[];
    lockedAxis?: 'x' | 'y' | null;
    /**
     * When `true`, the paperspace renderer sits the label ON the dimension line's midpoint (the
     * value reads inside the line) instead of the default placement, which offsets the label
     * perpendicular, clear of the line.
     *
     * Producers opt individual dims in for dense ruler rows where the value belongs inside the
     * line — the current use case is the wall-elevation breakdown, where section / gap / overall
     * widths render inline while thin separator thicknesses keep the default offset so they float
     * above the line. Absent (undefined) = default placement. Not persisted independently by any
     * consumer that doesn't already round-trip `IDimension` — additive shape, backwards-compatible.
     */
    labelInline?: boolean;
};
export type ITrace = IDimension;
export type ILeader = ITrace & {
    secondaryLines: {
        uuid: UUID;
        from: IPoint2d;
        to: IPoint2d;
    }[];
};
export type IText = IShape & {
    text: string;
    position: IPoint2d;
    rotation: number;
    width?: number;
    height?: number;
    align?: string;
    verticalAlign?: string;
    padding?: number;
};
export type ILabel = IText;
export type INumber = IShape & {
    rotation: number;
    position: IPoint2d;
    text: string;
    width: number;
    height: number;
    align: string;
    verticalAlign: string;
    draggable: boolean;
};
export type IBlock = IShape & {
    imgName: string;
    position: IPoint2d;
    width: number;
    height: number;
    rotation: number;
    distortable?: boolean;
    autoGenerated?: boolean;
};
export type IView = {
    imageUrl: string;
    rulerLines: IRulerLines;
    dimensions: dimensions;
    settings: I2DViewSettings;
    uuid: UUID;
    width: number;
    height: number;
    viewType: viewType;
    label?: string;
    wallViewType?: wallViewType;
    wallDistance?: number;
    index: number;
    fontSize: number;
    rotation: number;
    traces: {
        [key: string]: IDimension;
    };
    texts: {
        [key: string]: IText;
    };
    labels: {
        [key: string]: ILabel;
    };
    lines: {
        [key: string]: ILine;
    };
    blocks: {
        [key: string]: IBlock;
    };
    leaders: {
        [key: string]: ILeader;
    };
    numbers: {
        [key: string]: INumber;
    };
    tracesFS?: number;
    textsFS?: number;
    labelsFS?: number;
    leadersFS?: number;
    dimensionsFS?: number;
    numbersFS?: number;
    showBlocks?: boolean;
    showAutoBlocks?: boolean;
    showDimensions?: boolean;
    showLabels?: boolean;
    showLeaders?: boolean;
    showLines?: boolean;
    showTexts?: boolean;
    showTraces?: boolean;
    showNumbers?: boolean;
    textColor?: string;
    lineColor?: string;
    bgColor?: string;
    lineWidth?: number;
    extraSpace: IMarginSizes;
};
export type IPageView = {
    uuid: UUID;
    viewID: UUID;
    pageID: UUID;
    position: IPoint2d;
    rotation: number;
    sizes: sizes;
    fontSize: number;
    fixedScale?: number;
    tracesFS?: number;
    textsFS?: number;
    labelsFS?: number;
    numbersFS?: number;
    leadersFS?: number;
    dimensionsFS?: number;
    textColor?: string;
    bgColor?: string;
    lineColor?: string;
    lineWidth?: number;
    extraSpace: IMarginSizes;
};
export type CollageLayoutType = 'single' | 'split-h' | 'split-v' | 'quad' | 'triple-left' | 'triple-right' | 'triple-top' | 'triple-bottom' | 'hero-left' | 'hero-right' | 'hero-top' | 'hero-bottom' | 'main-sidebar' | 'main-footer' | 'main-header';
export type ICollageSlot = {
    uuid: UUID;
    pageViewUUID?: UUID;
    x: number;
    y: number;
    width: number;
    height: number;
};
export type ICollageConfig = {
    templateType: CollageLayoutType;
    slots: ICollageSlot[];
};
export type IPage = {
    uuid: UUID;
    isMain?: boolean;
    pageViews: {
        [key: string]: IPageView;
    };
    texts: {
        [key: string]: IText;
    };
    textsFS: number;
    collageConfig?: ICollageConfig;
};
export type IViews = {
    [key: string]: IView;
};
export type IPages = {
    [key: string]: IPage;
};
export type IDraggableView = {
    viewID?: UUID;
    positionOnImage?: IPoint2d;
};
export type IDraggableBlock = IBlock & {
    positionOnImage?: IPoint2d;
};
export type IDraggableText = IText & {
    positionOnImage?: IPoint2d;
};
export type IRulerLine = IDimension[];
export type IFloorRulerLines = {
    [key: string]: IRulerLine[];
};
export type IWallRulerLines = {
    [key in sideType]: IRulerLine[];
};
export type IRulerLines = IWallRulerLines | IFloorRulerLines;
export type IMarginSizes = {
    [key in sideType]: number;
};
export type IWallLinePoints = {
    [key in sideType]: pointViewExtended[][];
};
export type IFloorLinePoints = {
    [key: string]: pointViewExtended[][];
};
export type ILinePoints = IWallLinePoints | IFloorLinePoints;
export type dimensionPath = {
    side: string;
    line: number;
    position: number;
};
export type ISelectedShape = {
    uuid?: UUID;
    path?: dimensionPath;
    type: selectedShapeType;
    parentID: UUID;
};
export type IBlockSVG = {
    _id: string;
    name: string;
    source: string;
    distortable: boolean;
    isThin: boolean;
};
export type IPaperSpaceState = {
    selectedPageID?: UUID;
    selectedShape?: ISelectedShape;
    selectedViewID?: UUID;
    draggableView?: IDraggableView;
    draggableBlock?: IDraggableBlock | IDraggableText;
    views: IViews;
    pages?: IPages;
    pagesOrder?: UUID[];
    traceMode?: boolean;
    orthoMode?: boolean;
    leaderMode?: boolean;
    lineMode?: boolean;
    textMode?: boolean;
    pasteMode?: {
        isOn: boolean;
        copiedShape: IText | IBlock | null;
    };
    currentScale?: number;
    stage?: 1 | 2;
    pdf?: boolean;
    pdfLocal?: boolean;
    loadingImages?: null | number;
    showMainPage?: boolean;
    fontSize?: number;
    textColor?: string;
    bgColor?: string;
    lineWidth?: number;
    lineColor?: string;
    previewHeight?: number;
    cameraDistanceFromWall?: inches;
    offsetLeft?: inches;
    offsetRight?: inches;
    wallViewType?: wallViewType;
    blocks?: undefined | IBlockSVG[];
    snapping?: snapping;
};
export interface IViewProperties {
    dimensionsFS?: number;
    textsFS?: number;
    tracesFS?: number;
    labelsFS?: number;
    leadersFS?: number;
    numbersFS?: number;
    width?: number;
    height?: number;
    extraSpace?: IMarginSizes;
    fontSize?: number;
    fixedScale?: number;
    position?: IPoint2d;
}
export type IAreaHeader = {
    image?: string;
    main_page_image?: string;
    orientation?: 'Landscape' | 'Portrait';
    width?: number;
    height?: number;
    meta?: {
        [key: string]: string;
    };
};
/**
 * Paperspace views grouped by their owning multiCloset systemId. Produced by the export
 * pipeline that iterates multiCloset systems and renders per-system views — primary producer
 * is `Designer3DView.createAllViews` in `@moon/designer3d`.
 *
 * The wrapper object per entry (`{ views: IViews }`) leaves room for per-system metadata
 * (label, count, thumbnail, …) to be added later without changing this signature.
 *
 * Inner `views` reuses `IViews` deliberately so any per-system entry can be handed directly to
 * `<PaperSpaceProvider data={…}>` — `IPaperSpaceState.views` is the only required field on
 * that type, so the partial shape `{ views: IViews }` typechecks as a full `IPaperSpaceState`.
 * See `PaperSpaceWrapper` (documents step in `apps/mobile-capacitor`) for the flow that
 * exploits this. If a future required field is ever added to `IPaperSpaceState`, this
 * pass-through will typecheck-but-crash-at-runtime and needs updating.
 *
 * Flat-map recipes for callers that don't want the grouping:
 *   Merge to `IViews`:
 *     `Object.values(x).reduce<IViews>((acc, { views }) => ({ ...acc, ...views }), {})`
 *   Materialize to `IView[]`:
 *     `Object.values(x).flatMap(({ views }) => Object.values(views))`
 */
export type IViewsBySystem = Record<UUID, {
    views: IViews;
}>;
