import type { AppData, IOrbitControls, IOrthoCamera, IPerspectiveCamera } from '../../declarations/appData';
import type { ICatalog, ICatalogClassifications } from '../../declarations/Catalogs';
import type { UUID } from '../../declarations/core';
import type { IAreaHeader, IPaperSpaceState } from '../../declarations/PaperSpace';
import type { SystemsAPI } from '../../declarations/systems';
import type { CapturedRoom } from '../../helpers/converter/roomplan/types';
export declare const asUuid: (value: string) => UUID;
export declare const TEST_FLOORPLAN_ID: UUID;
export declare const TEST_STAGE_ID: UUID;
export declare const createMinOrthoCamera: () => IOrthoCamera;
export declare const createMinPerspectiveCamera: () => IPerspectiveCamera;
export declare const createMinOrbitControls: () => IOrbitControls;
export declare const createMinAppData: () => AppData;
/** mapMaterials() calls .filter() on all four arrays. */
export declare const createMinMaterialsAPI: () => {
    Surfaces: unknown[];
    Materials: unknown[];
    Mouldings: unknown[];
    Hardware: unknown[];
};
export declare const createMinLooksAPI: () => {};
export declare const createMinModels3DAPI: () => {};
export declare const createMinCatalogClassifications: () => ICatalogClassifications;
export declare const createMinCatalog: () => ICatalog;
export declare const createMinPaperSpaceAPI: () => IPaperSpaceState;
export declare const createMinAreaHeaderAPI: () => IAreaHeader;
export declare const createMinRoomplanData: () => CapturedRoom | null;
export declare const createMinSystemData: () => SystemsAPI;
export declare const createMinDomElement: () => HTMLDivElement;
export declare const mockAppData: AppData;
export declare const mockLooksAPI: unknown;
export declare const mockMaterialsAPI: unknown;
export declare const mockModels3DAPI: unknown;
export declare const mockCatalogClassifications: ICatalogClassifications;
export declare const mockPrivateCatalog: ICatalog;
export declare const mockMasterCatalog: ICatalog;
export declare const mockPaperSpaceAPI: IPaperSpaceState;
export declare const mockAreaHeaderAPI: IAreaHeader;
export declare const mockRoomplanData: CapturedRoom | null;
export declare const mockSystemData: SystemsAPI;
export declare const mockDomElement: HTMLDivElement;
