import { NodeConfig } from '../../../declarations';
import { CoreDesigner } from '../../../designer-core';
import { AdjustableBox } from '../components/AdjustableBox';
import { AdjustableExtrusion } from '../components/AdjustableExtrusion';
import { BoxContainer } from '../components/BoxContainer';
import { Carcass } from '../components/Carcass';
import { Ceiling2D } from '../components/Ceiling2D';
import { Countertop } from '../components/Countertop';
import { CrownMolding } from '../components/CrownMolding';
import { Edgebanding } from '../components/Edgebanding/index';
import { Floor2D } from '../components/Floor2D';
import { Floorplan } from '../components/Floorplan';
import { Frame } from '../components/Frame';
import { FreeBoxContainer } from '../components/FreeBoxContainer';
import { GateFrame } from '../components/GateFrame';
import { Glass } from '../components/Glass';
import { Image } from '../components/Image';
import { Item } from '../components/Item';
import { LaminateBox } from '../components/LaminateBox';
import { MiteredPanel } from '../components/MiteredPanel';
import { ApplianceModel } from '../components/Model/ApplianceModel';
import { HingeModel } from '../components/Model/HingeModel';
import { OtherModel } from '../components/Model/OtherModel';
import { Molding, SimpleMolding } from '../components/Molding';
import { MountLine } from '../components/MountLine';
import { MountPlane } from '../components/MountPlane';
import { MountPoint } from '../components/MountPoint';
import { Panel } from '../components/Panel';
import { Part } from '../components/Part';
import { Point } from '../components/Point';
import { PointLight } from '../components/PointLight';
import { RawPanel } from '../components/RawPanel';
import { Room } from '../components/Room';
import { RoomSegment } from '../components/RoomSegment';
import { ShapedBoxContainer } from '../components/ShapedBoxContainer';
import { SpotLight } from '../components/SpotLight';
import { Stage } from '../components/Stage';
import { Tiles } from '../components/Tiles';
import { ToeKickPanel } from '../components/ToeKickPanel';
import { Valance } from '../components/Valance';
import { Wall2D } from '../components/Wall2D';
import { WindowFrame } from '../components/WindowFrame';
export type Node = Item | Part | Panel | Edgebanding | Floorplan | Stage | Wall2D | Floor2D | Ceiling2D | Point | RoomSegment | Room | AdjustableBox | AdjustableExtrusion | BoxContainer | Carcass | Countertop | CrownMolding | Frame | FreeBoxContainer | GateFrame | Glass | Image | LaminateBox | MiteredPanel | MountPoint | MountPlane | MountLine | OtherModel | ApplianceModel | HingeModel | Molding | SimpleMolding | PointLight | RawPanel | ShapedBoxContainer | SpotLight | Tiles | ToeKickPanel | Valance | WindowFrame;
declare const createNode: (config: NodeConfig, core: CoreDesigner) => Node;
export default createNode;
