import type { AppData } from '../../declarations/appData';
import type { ICatalog, ICatalogClassifications } from '../../declarations/Catalogs';
import type { looksAPI, materialsAPI, models3DAPI } from '../../declarations/Loader';
import type { IAreaHeader, IPaperSpaceState } from '../../declarations/PaperSpace';
import type { IProjectSettings } from '../../declarations/ProjectSettings';
import type { SystemsAPI } from '../../declarations/systems';
import type { SectionContentProfile } from '../multiCloset/types';
import type { CapturedRoom } from './roomplan/types';
export * from './roomplan';
export * from './package';
export type AllData = {
    appData: AppData;
    masterCatalog: ICatalog;
    privateCatalog: ICatalog;
    projectSettings: IProjectSettings;
    materials: materialsAPI;
    looks: looksAPI;
    models3D: models3DAPI;
    catalogClassifications: ICatalogClassifications;
    paperSpace: IPaperSpaceState;
    areaHeader: IAreaHeader;
    roomplanData?: CapturedRoom;
    systemData?: SystemsAPI;
    sectionOptions: SectionContentProfile[];
};
